sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2

install:
  - composer install --prefer-dist

before_script:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.jso

script:
  - composer cs
  - composer test

cache:
  directories:
    - $HOME/.composer/cache/files
